endpoints:
  all:
    sensitive: false

jackson:
  serialization-inclusion: ALWAYS

micronaut:
  router:
    static-resources:
      rapidoc:
        paths: "classpath:META-INF/rapidoc"
        mapping: /**
      swagger:
        paths: "classpath:META-INF/swagger"
        mapping: /swagger/**
